### ISSUE TITLE
yerna install does not seem to work on windows

### ISSUE THREAD

**Issue by michael-yx-wu** [palantir/yerna#26] opened 2017-06-23 06:23 UTC
Knowing us, I doubt we tested this thing on a Windows machine. This is the stack trace that I get when trying to run `yerna install --parallel 1 -- --pure-lockfile`:

```
yerna: running yarn install --pure-lockfile for 5 package(s)
yerna: Error: spawn yarn ENOENT
yerna:     at exports._errnoException (util.js:1050:11)
yerna:     at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
yerna:     at onErrorNT (internal/child_process.js:367:16)
yerna:     at _combinedTickCallback (internal/process/next_tick.js:80:11)
yerna:     at process._tickCallback (internal/process/next_tick.js:104:9)
yerna: unexpected error, exiting suddenly!
yerna: this is probably a bug in Yerna itself, please file an issue!
yerna: NOTE: package.jsons or links may be in an inconsistent state
yerna: NOTE: child processes may be abandoned
yerna: failed after 0.03s
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

OS: Windows 10 Enterprise 
OS Build: 14393.066
node version: 7.9.0
npm version: 4.2.0
yarn version: 0.24.5

Note: node/npm installed / being managed by `nvm-windows`

**Comment by seansfkelley** [comment] 2017-06-23 18:16
Duplicate of #13.

**Closed by seansfkelley** 2017-06-23 18:16 UTC
